# Generated by Django 3.2.25 on 2025-03-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20250312_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='_products_category_sub_categories_+', to='products.Category'),
        ),
    ]
