# Generated by Django 4.0 on 2025-04-01 17:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_image_url_product_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
